# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: MingXingTeam's Blog
subtitle: free mind free life
description: Talk is cheap, show me your product
author: MaoXingXing
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mingxingteam.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
tag_dir: tags
archive_dir: archives
category_dir: categories

# Social links
social:
  GitHub: https://github.com/MingXingTeam
  Twitter: 
  Weibo: http://weibo.com/mingxingteam
  DouBan: http://www.douban.com/people/54471260/
  ZhiHu: http://www.zhihu.com/people/feng-zi-63-44

# Specify the date when the site was setup
since: 2015

# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
max_open_file: 100
post_asset_folder: false
relative_link: false
future: true
auto_spacing: false
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  backtick_code_block: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives 默认值为2，这里都修改为1，相应页面就只会列出标题，而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server 不修改
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 3
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

Plugins:
- hexo-generator-feed
- hexo-generator-sitemap

# 配置站点文件
feed:
  type: atom
  path: atom.xml
  limit: 20

# head pic
avatar: /uploads/avatar.jpg

# Disqus Disqus插件，我们会替换成“多说”，不修改
disqus_shortname:
duoshuo_shortname: mxt2014

# 多说热评文章 true 或者 false
duoshuo_hotartical: true

# JiaThis 分享服务
jiathis: true

# 百度分享服务
baidushare: true

# 多说分享服务
duoshuo_share: true

# title, chinese available
links_title: Links

links:
  TaoBaoUED: http://ued.taobao.org/blog/
  AliUED: http://www.aliued.com/

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: ssh://git@github.com/MingXingTeam/MingXingTeam.github.io
  branch: master